### ISSUE TITLE
feature request: provide means to make replies configurable

### ISSUE THREAD

**Issue by mgumz** [travelping/hello_test_server#2]
use case: a (testing) client sends a request. the user wants to define the reply in advance in a simple way. maybe a .json file.

the request looks like

```
{"jsonrpc":"2.0","id":"x","method":"foo.bar"}
```

the reply should be delivered from a folder or the like:

```
replies/
    foo.bar/
            reply.json
            reply2.json
    other.method/
                 reply.json
```

**Comment by liveforeverx** [comment]
CC: Only, that all informed, inclusive me: @umatomba , @surik , @0xAX , @liveforeverx

**Comment by surik** [comment]
@mgumz how test_server should to choose reply.json or reply2.json for `foo.bar` method?

**Comment by surik** [comment]
What you think about if we'll have folder called `priv/replies` and if method is `foo.bar` server will send `priv/replies/foo/bar.json` in reply?

Should we use `params` for choosing reply? I think it is ambiguous

**Comment by mgumz** [comment]
folder: i am not sure that "priv/" is a good folder name, allthough i am aware of the fact that "priv/" is kind of "convention" in the elixir world. the hello_test_server should also be used by non-elixir-folks to have means to deliver "mocked" responses without really deep knowledge of elixir and the like. also: think more like "apache": apache delivers stuff from folders not associated with "apache". you tell apache a folder-name and it delivers stuff from there. i would prefer a command-line like "--replies" or the like.

what to send: i really would pick a folder-name equal to the method name. this allows the user to let the server to send in round-robin fashin reply.json and reply2.json and reply3.json.

params: i am not sure yet how to specify params for the reply. maybe as part of the name of the reply:  reply_b64:param-string.json ... if the b64:param-string is missing than only "reply.json" will "match".

**Comment by liveforeverx** [comment]
priv is a good place for erlang world. There is simple 2 folders, which will be installed on running system. ebin(erlang beam files), priv(all other, what can be taken to running release, like some files(for web static files), c-compiled libraries, the same for json files).

**Comment by liveforeverx** [comment]
CLI can of course use another location.

**Comment by surik** [comment]
> params: i am not sure yet how to specify params for the reply. maybe as part of the name of the reply: reply_b64:param-string.json ... if the b64:param-string is missing than only "reply.json" will "match".

Do you mean base64 encoding for params? I think it is bad way for json

**Comment by mgumz** [comment]
@surik: base64(params) ->  reply_ad81z2jasuzasudzuas.json

otherwise you won't have a filename that will survive, lets say, a regular contact with ntfs. something like  reply_x=1_y=2_z=bar.json is instable. one would have to come up with all kind of silly hacks to enforce a-zA-Z0-9 and lists and dicts and this and that.

full fledged example:

request:
    {"jsonrpc":"2.0","id":"1","method":"foo.bar","params":{"key":"value","other":[1,2,3,"10"]}}

reply:
    replies/foo.bar/reply_eyJqc29ucnBjIjoiMi4wIiwiaWQiOiIxIiwibWV0aG9kIjoiZm9vLmJhciIsInBhcmFtcyI6eyJrZXkiOiJ2YWx1ZSIsIm90aGVyIjpbMSwyLDMsIjEwIl19fQo=.json

problem: length of filename. alternative: sha1(params):

```
replies/foo.bar/reply_0e30cf552baadf6b03271f40cae7463a8585a0c8.json
```

**Comment by surik** [comment]
@mgumz 
1) `{"key":"value", "other":[1,2,3,"10"]}` and `{"other":[1,2,3,"10"], "key":"value"}` are equal but have different hash
2) this is difficult to use, you should to have some tools to generate and edit such replies

**Comment by mgumz** [comment]
1) correct, but irrelevant: the user's use case is not to test how stable the order of the parameters is in hello :) the user wont' randomize the json just to make his own life miserable.

2) correct. that's also the reason why i said "i am not sure yet how to specify params for the reply." ... but i dont have any other idea. tooling: idea: if hello_test_server logs to stdout/stderr the incoming request, the parameters AND the resulting hash, the user might just pick that up and provide the right file.

**Comment by surik** [comment]
Hi @mgumz
I had some time for thinking about this request and I would like to offer a solution

We have 2 modes for mocking methods
1. _Simple_ - matching only by method (this is that you offered in your first message)
2. _Extended_ - you will be writing matching logic in Elixir language

First method, I think, is very clear, but I should to give example:
Let we have `priv/replies` structure:

```
replies/
    abc.a.c/
        reply.json
    foo.bar/
        reply1.json
        reply2.json
```

If method is `abc.a.c` then reply is always contain `replies/abc/a.c/reply.json`.
If method is `foo.bar` we send reply in round robing mode `replies/foo.bar/reply1.json` or `replies/foo.bar/reply2.json`
If method doesn't match we will send "not_found"

Second method is more difficult. If you want to write your own logic for method `foo/bar` you should to have `priv/replies` structure like this:

```
replies/
    abc.a.c/
        ...
    foo.bar.ex
```

When test server received request with method `foo/bar` it will forward this request to the script and when script have handled with this request test server will send back this response

foo.bar.ex might look like

``` elixir
case params do
  %{"key" => 1} -> "response"
  %{"key" => 2} -> "response2"
  _ -> "unknown"
end
```

**Comment by mgumz** [comment]
yah, lets roll with this.
